pipeline {
    agent { label 'docker' }

    stages {

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t my-nginx .'
            }
        }

        stage('Load Image Into KIND') {
            steps {
                sh 'kind load docker-image my-nginx'
            }
        }

        stage('Deploy To Kubernetes') {
            steps {
		dir('frontend') {
                sh 'kubectl apply -f deployment.yaml'
                sh 'kubectl apply -f service.yaml'
                }
            }
        }

    }
}
